start.html
This PR updated all links according to current tutorial examples on `start.html`
=> Update start page

index.html
This PR updated:
1. release roadmap.
2. github repos.
3. new features of v0.3.0.
4. highlight tutorials and examples.
=> Update index page for v0.3.0 release

index.html, start.html
Signed-off-by: Nic Ma <nma@nvidia.com>
This PR updated the links of workflows in the web pages.
=> Update workflows examples link

css/main.css, docs.html, footer.html, nav.html
- Added Docs Page
- Added Height fix to make footer float at the bottom for docs page
- Fixed Nav and Footer bar to update docs link
- Add Medium link to Nav bar
- Fix show-menu class to show full bar on mobile
=> Docs Pages and General CSS fixes

index.html
- Update Banner to include release info and links for Core, Deploy, and Label.
- Update timeline for MONAI Core at bottom of page
=> Update MONAI website with new release information

about.html, community.html, docs.html, start.html
Streamlined Getting Started Page
- Added overview with Quick Links
- Reduce the number of tutorials to highlight main features
- Added links to a more extensive tutorial list (on Github)
- Remove the Bootcamp section and integrated it into the top description
- Updated HTML Title attribute to accurately track pages for Google Analytics
=> Streamlined Getting Started Page

start.html
This is a reimplementation of the simplification of the Getting Started Guide.  The Agency we're working with for redesign needs this updated so it'll be pushed immediately.
=> Reimplement simplify of getting started page after recent changes

started.html
Signed-off-by: Andres <diazandr3s@gmail.com>
=> Update Started file - Updated MONAI Label links

started.html
Signed-off-by: Andres Diaz-Pinto <diazandr3s@gmail.com>
=> Update MONAI Label links

research/auto3dseg.html, research/coplenet-pneumonia-lesion-segmentation.html, research/dints.html, research/lamp-automated-model-parallelism.html, research/swin-unetr.html, research/unetr-btcv-multi-organ-segmentation.html, research/unetr.html
- adds a redirection for auto3dseg
- `master` -> `main`
Signed-off-by: Wenqi Li <wenqil@nvidia.com>
=> adds auto3dseg url

assets/css/tailwind.css, deploy.html
Update MONAI Deploy Infra ordering and update links for MONAI Deploy flow + Docs and Getting Started
=> Updates to MONAI Deploy page

apps/MetricsReloaded.html
Signed-off-by: Wenqi Li <wenqil@nvidia.com>
=> adds url for metrics reloaded

index.html
Update Core to 1.1, Label to 0.6, and total downloads to 800k on the counter.
=> Update Versions and Download Numbers

.github/workflows/fetch.py, templates/model-template.html
Updated template and fetch script to include model versions.
=> Update Model Zoo to include version numbers

started.html
Fix broken links and remove MIS for Deploy Getting Started
=> Fix broken links and remove MIS for Deploy Getting Started

research/maisi.html
=> add maisi link

package.json
Fixed npm serving of page during development
=> Add dev:serve option

README.md, assets/js/main.js, components/head.html, components/header.html, components/scripts.html
Implements a flexible banner system for site-wide announcements and surveys, while removing WOW.js animation library to improve performance.
- Added customizable banner component with priority-based display, persistent dismissal, and automatic header adjustment
- Removed WOW.js and animate.css dependencies to reduce bundle size
- Updated documentation with banner configuration examples
=> Add banner system for announcements and remove WOW.js animations

404.html, about.html, core.html, deploy.html, index.html, label.html, mayo-case-study.html, mayo-siemens-case-study.html, model-zoo.html, start.html, wg_deploy.html, wg_developers.html, wg_education.html, wg_evaluation_benchmark.html, wg_federated_learning.html, wg_human_ai_interaction.html, wg_ophthalmology.html, wg_outreach_adoption.html, wg_ultrasound.html, working-groups.html
- Fixed duplicate navbar appearing on pages after banner system merge
- Removed redundant include comment patterns that were causing components to be included twice
=> Fix duplicate navbar issue

.claude/settings.local.json, components/header.html, deploy.html, index.html, successstories.html
Create success stories and include in nav bar.  Also updated index and deploy pages to include the new use case in their relevant section.
=> Create success stories and update navigation
